# Generated by Django 5.2.7 on 2025-11-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_brand_name_alter_brand_name_ar_and_more'),
        ('wishlist', '0003_remove_wishlist_product_wishlist_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='pwish', to='core.product'),
        ),
    ]
