# Generated by Django 5.2.5 on 2025-09-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.RemoveField(
            model_name='review',
            name='subject',
        ),
        migrations.AddField(
            model_name='product',
            name='bestseller',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
