# Generated by Django 5.2.5 on 2025-09-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_product_options_remove_review_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bestseller',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
