# Generated by Django 5.2.5 on 2025-09-20 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_product_bestseller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(blank=True, max_length=300, verbose_name='Review'),
        ),
    ]
