# Generated by Django 5.1.5 on 2025-06-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_product_brand_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug_ar',
            field=models.SlugField(blank=True, max_length=150, null=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug_en',
            field=models.SlugField(blank=True, max_length=150, null=True, verbose_name='Slug'),
        ),
    ]
