# Generated by Django 5.1.5 on 2025-06-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_slug_ar_product_slug_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='name_ar',
            field=models.CharField(max_length=150, null=True, verbose_name='Brand Name'),
        ),
        migrations.AddField(
            model_name='brand',
            name='name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Brand Name'),
        ),
        migrations.AddField(
            model_name='brand',
            name='slug_ar',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='slug_en',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ar',
            field=models.CharField(max_length=150, null=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug_ar',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='slug_en',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
