# Generated by Django 5.2.5 on 2025-09-28 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_review_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variation',
            options={'ordering': ('product__name',)},
        ),
    ]
