# Generated by Django 5.1.5 on 2025-06-26 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_brand_name_ar_brand_name_en_brand_slug_ar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='slug_ar',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='slug_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug_ar',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug_en',
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brands', to='core.brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='core.category'),
        ),
    ]
