# Generated by Django 5.2.7 on 2025-11-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_variation_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Brand Name'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name_ar',
            field=models.CharField(db_index=True, max_length=150, null=True, verbose_name='Brand Name'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name_en',
            field=models.CharField(db_index=True, max_length=150, null=True, verbose_name='Brand Name'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_ar',
            field=models.CharField(db_index=True, max_length=150, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_en',
            field=models.CharField(db_index=True, max_length=150, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='Slug'),
        ),
    ]
