# Generated by Django 5.2.5 on 2026-08-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_brand_name_alter_brand_name_ar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_ar',
            field=models.CharField(db_index=True, max_length=150, null=True, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(db_index=True, max_length=150, null=True, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='key',
            field=models.CharField(choices=[('color', 'color'), ('size', 'size')], db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='variation',
            name='value',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Value'),
        ),
    ]
