# Generated by Django 5.1.5 on 2025-06-26 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_brand_name_ar_brand_name_en_category_name_ar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug_ar',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug_en',
        ),
    ]
