# Generated by Django 5.1.5 on 2025-07-14 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img',
            field=models.ImageField(default='profile-2.png', upload_to='ProfileImage'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
