# Generated by Django 5.1.5 on 2025-02-14 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_contact_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='profile-2.png', upload_to='ProfileImage'),
        ),
    ]
