# Generated by Django 5.2.5 on 2025-10-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderitem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('PayPal', 'PayPal'), ('Stripe', 'Stripe'), ('CashOnDelivery', 'CashOnDelivery')], max_length=50),
        ),
    ]
