# Generated by Django 5.1.5 on 2025-06-13 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderitem_color_alter_orderitem_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled'), ('Refunded', 'Refunded')], default='Pending', max_length=150),
        ),
    ]
