# Generated by Django 5.1.5 on 2025-06-13 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('Stripe', 'Stripe'), ('Paypal', 'Paypal'), ('CashOnDelivery', 'CashOnDelivery')], max_length=50),
        ),
    ]
