# Generated by Django 5.2.5 on 2026-09-19 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Uncomplete', 'Uncomplete'), ('Pending', 'Pending'), ('Paid', 'Paid'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled'), ('Refund Requested', 'Refund Requested'), ('Refunded', 'Refunded'), ('Refund Declined', 'Refund Declined')], default='Uncomplete', max_length=150, verbose_name='Status'),
        ),
    ]
