# Generated by Django 5.1.5 on 2025-06-16 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('Stripe', 'Stripe'), ('InstaPay', 'InstaPay'), ('CashOnDelivery', 'CashOnDelivery')], max_length=50),
        ),
    ]
